django_blog/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib import admin
from posts import views

from accounts.views import (
    login_view,
    logout_view,
    register_view
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^', include("posts.urls", namespace='posts')),
    url(r'^api/posts/', include("posts.api.urls", namespace='posts_api')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/api/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    PostListAPIView,
    PostDetailAPIView,
    PostDeleteAPIView,
    PostUpdateAPIView,
    PostCreateAPIView,
)

urlpatterns = [
    url(r'^create/$', PostCreateAPIView.as_view(), name='create'),
    url(r'^$', PostListAPIView.as_view(), name='list_api'),
    url(r'^(?P<pk>\d+)/$', PostDetailAPIView.as_view(), name='detail_api'),
    url(r'^(?P<pk>\d+)/edit/$', PostUpdateAPIView.as_view(), name='update_api'),
    url(r'^(?P<pk>\d+)/delete/$', PostDeleteAPIView.as_view(), name='delete_api'),

]

posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='list'),
    url(r'^create/$', views.post_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.post_update, name='post_update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.post_delete, name='delete'),

]

posts/models.py
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify


from markdown_deux import markdown
from comments.models import Comment
from .utils import get_read_time

# Create your models here.
# MVC Model View Controller


#Post.objects.all()
#Post.objects.create(user=user, title="Some time")

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
    PostModel = instance.__class__
    new_id = PostModel.objects.order_by("id").last().id + 1
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object,
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "%s/%s" % (new_id, filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120) #max_length=120
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
        null=True,
        blank=True,
        width_field="width_field",
        height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time =  models.IntegerField(default=0) # models.TimeField(null=True, blank=True) #assume minutes
    update = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:post_detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-timestamp", "-update"]


    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms
from .models import Post
from pagedown.widgets import PagedownWidget

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
            'draft',
            'publish'
        ]

posts/api/views.py
from rest_framework.generics import (
    ListAPIView,
    CreateAPIView,
    RetrieveAPIView,
    UpdateAPIView,
    DestroyAPIView,
    RetrieveUpdateAPIView
)

from rest_framework.pagination import (
    LimitOffsetPagination,
    PageNumberPagination,
)

from rest_framework.filters import (
    SearchFilter,
    OrderingFilter,

)
from django.db.models import Q
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly
)

from posts.models import Post
from .permissions import IsOwnerOrReadOnly
from .pagination import PostLimitOffsetPagination, PostPageNumberPagination

from .serializers import (
    PostListSerializer,
    PostDetailSerializer,
    PostCreateUpdateSerializer
)


class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    permission_classes = [IsAuthenticated, IsAdminUser]
    lookup_field = 'pk'

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class PostListAPIView(ListAPIView):
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter]
    search_fields = ['title', 'content', 'user__first_name']
    pagination_class = PostPageNumberPagination #PageNumberPagination

    def get_queryset(self, *args, **kwargs):
        queryset_list = Post.objects.all()
        query = self.request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(
                Q(title__icontains=query)|
                Q(content__icontains=query)|
                Q(user__first_name__icontains=query)|
                Q(user__last_name__icontains=query)
            ).distinct()
        return queryset_list

class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'pk'


class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    lookup_field = 'pk'
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'pk'
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

posts/views.py
try:
    from urllib.parse import quote_plus #python 3
except:
    pass

from django.db.models import Q


from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from comments.forms import CommentForm
from comments.models import Comment
from .forms import PostForm
from .models import Post


# Create your views here.
def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        # message success
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(instance.get_absolute_url())
    else:
        messages.error(request, "Not Successfully Created")
    context = {
        "form": form,
    }
    return render(request, "post_form.html", context)

def post_detail(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)
    if instance.publish > timezone.now().date() or instance.draft:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = quote_plus(instance.content)

    initial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id
    }

    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get('object_id')
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
                                                user = request.user,
                                                content_type = content_type,
                                                object_id = obj_id,
                                                content = content_data,
                                                parent = parent_obj,
                                            )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
    comments = instance.comments
    context = {
        "instance": instance,
        "title": instance.title,
        "share_string": share_string,
        "comment_form":form,
        "comments": comments,
    }
    return render(request, "post_detail.html",context)

def post_list(request):
    today = timezone.now().date()
    queryset_list = Post.objects.active()#.order_by("-timestamp")
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all();

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()
    paginator = Paginator(queryset_list, 8) # Show 25 contacts per page

    page_request_var = "page"
    page = request.GET.get(page_request_var)

    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
		# If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    context = {
        "object_list": queryset,
        "title": "List",
        "page_request_var": page_request_var,
        "today": today
    }
    return render(request, "post_list.html",context)

def post_update(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "instance": instance,
        "title": instance.title,
        "form": form
    }
    return render(request, "post_form.html",context)

def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    message.success(request, "Successfully deleted")
    return redirect("list")

templates/base.html
{%load staticfiles %}

<html>
<head>
  <title>{% block head_title %}Try Django 1.9{% endblock head_title %}</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" >

  <link rel='stylesheet' href='{% static "css/base.css" %}' />
<style>
{%block style%}{%endblock style%}
</style>
{%block head_extra%}{%endblock head_extra%}
</head>
<body>
  <div id="fb-root"></div>
  <script>(function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s);
    js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>


{%include "messages_display.html"%}
<div class='container'>
  <ol class='breadcrumb'>
    <li><a href='{%url "posts:list" %}'>Home</a></li>
    {%block post_detail_link%}
    {%endblock%}

    {%if not request.user.is_authenticated%}
    <li class='pull-right'><a href='{% url "register" %}'>Register</a></li>
      <li class='pull-right'><a href='{% url "login" %}'>Login</a></li>
      {% else %}
      <li class='pull-right'><a href='{% url "logout" %}'>Logout</a></li>
      {% endif %}
  </ol>
{%block content%}{%endblock content%}
</div>


<script
  src="http://code.jquery.com/jquery-1.12.4.js"
  integrity="sha256-Qw82+bXyGq6MydymqBxNPYTaUXXq7c8v3CwiYwLLNXU="
  crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.17/marked.min.js"></script>

<script type="text/javascript">
  $(document).ready(function(){
    $(".content-markdown").each(function(){
      var content = $(this).text()
      var markedContent = marked(content)
      $(this).html(markedContent)
    })
    $(".post-detail-item img").each(function(){
      $(this).addClass("img-responsive");
    })
    var titleItem = $("#id_title");
    $("#preview-title").text(titleItem.val())

    var contentInput = $("#id_content");

    function setContent(value){
      var markedContent = marked(value)
        $("#preview-content").html(markedContent)
        $("#preview-content img").each(function(){
          $(this).addClass("img-responsive")
        })
    }
    setContent(contentInput.val())

    contentInput.keyup(function(){
      var newContent = $(this).val()
      setContent(newContent)
    })
    var titleInput = $("#id_title")

    function setTitle(value){
      $("#preview-title").text(value)
    }
    setTitle(titleInput.val())
    titleInput.keyup(function(){
      var newContent = $(this).val()
      setTitle(newContent)
    })
  })
</script>

</body>
</html>

templates/form.html
{%extends "base.html"%}
{%load crispy_forms_tags %}



{%block content%}
<div class="col-sm-6 col-sm-offset-3">
<h1>{{title}}</h1>
<hr/>

<form method='POST' action='' enctype="multipart/form-data">{%csrf_token%}
{{form| crispy}}
<input type='submit'  class="btn btn-default" value="{{title}}"/>
</form>
</div>
{%endblock content%}

templates/messages_display.html
{%if messages%}
  <div class="messages">
    <ul class="messages">
      {%for message in messages%}
      <li{%if message.tags%} class="{{message.tags}}"{%endif%}>{%if "html_safe" in message.tags%}{{message|safe}}{%else%}{{message}}{%endif%}</li>
      {%endfor%}
    </ul>
  </div>
{%endif%}

templates/post_detail.html
{%extends "base.html"%}
{% load urlify%}
{% load crispy_forms_tags %}


{%block head_title%}
{{instance.title}} | {{block.super}}
{%endblock head_title%}


{%block post_detail_link%}
  <li><a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a></li>
{%endblock%}

{%block content%}
<div class='col-sm-6 col-sm-offset-3'>
  {%if instance.image%}
  <img src="{{ instance.image.url }}" class='img-responsive'/>
  {%endif%}
<h1>{{title}} <small>{%if instance.draft%}<span style='color:red;'>Draft </span>{%endif%}{{instance.publish}}</small></h1>

<p>Read time: {% if instance.read_time <= 1 %} < 1 Minute {% else %}{{ instance.read_time }} minutes {% endif %}</p>
{% if instance.user.get_full_name %}
  <p>Author: {{instance.user.get_full_name }}</p>
{%endif%}


<p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
<hr/>
</p>

<!-- <p>
<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
Facebook
</a>
<a href="https://twitter.com/home?status={{ object.content|truncatechars:80|urlify }}%20{{ request.build_absolute_uri }}">
Twitter
</a>
<a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>
<a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ object.title }}&summary={{ share_string }}&source={{ request.build_absolute_uri }}">
Linkedin
</a>
<a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&title={{ share_string }}.">Reddit</a>
</p> -->
<div class='row'>
<div class='col-sm-12'>

  <div class='post-detail-item'>{{ instance.get_markdown }}</div>

<hr/>
<br/>
<div>

    <p class='lead'>Comments</p>
    {% if request.user.is_authenticated %}
    <form method="POST" action="."> {% csrf_token %}
        {{ comment_form|crispy }}
        <input type='submit' value='Post comment' class='btn btn-default'>
    </form>
    {% else %}
    <p>You must login to comment </p>
    {% endif %}
    <hr/>
    {% for comment in comments %}

    <blockquote>
      <p>{{ comment.content }}</p>
      <footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} | {% endif %} <a class='comment-reply-btn' href='#'>Reply</a> | <a class='' href='{{ comment.get_absolute_url }}'>Thread</a></footer>
      <div class='comment-reply'>
          {% for child_comment in comment.children %}
            <blockquote>
            <p>{{ child_comment.content }}</p>
            <footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago</footer>
            </blockquote>
         {% endfor %}
         {% if request.user.is_authenticated %}
        <form method="POST" action="."> {% csrf_token %}
            {{ comment_form|crispy }}
            <input type='hidden' name='parent_id' value='{{ comment.id }}'>
            <input type='submit' value='Reply' class='btn btn-default'>
        </form>
        {% else %}
    <p>You must login to comment </p>
    {% endif %}
    </div>

    </blockquote>

    <hr/>
    {% endfor %}
</div>




</div>
</div>
</div>

{%endblock content%}

templates/post_form.html
{%extends "base.html"%}
{%load crispy_forms_tags %}


{%block head_extra%}
{{form.media}}

{%endblock head_extra%}



{%block content%}
<div class='col-sm-6'>
 <h1>Preview</h1>
<hr/>
 <div class="content-preview">
   <h3 id="preview-title"></h3>
   <p id="preview-content"></p>
</div>
</div>
<div class="col-sm-6">
<h1>Form</h1>
<hr/>
<form method='POST' action='' enctype="multipart/form-data">{%csrf_token%}
{{form | crispy}}
<input type='submit' class='btn btn-default' value="Create Post"/>
</form>
</div>
{%endblock content%}

templates/post_list.html
{% extends "base.html" %}
{% block content %}


<div class='col-sm-6 col-sm-offset-3'>
    <h1>{{ title }}</h1>
<form method='GET' action='' class='row'>
        <div class='col-sm-6'>
            <div class='input-group'>
                <input class='form-control' type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
                <span class='input-group-btn'>
                    <!-- <input class='btn btn-default' type='submit' value='Search' /> -->
                    <button class='btn btn-default' type='submit'>Search <i class="fa fa-search"></i></button>
                </span>
            </div>
        </div>
</form>
{% for obj in object_list %}
<div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">
        {% if obj.image %}
         <img src='{{ obj.image.url }}' class='img-responsive' />
        {% endif %}
      <div class="caption post-detail-item">
        {% if obj.draft %}<h3>Staff only: Draft</h3>{% endif %} {% if obj.publish > today %}<h3>Staff Only: Future Post</h3>{% endif %}
        <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a> <small>{{ obj.publish }}</small></h3>
        {% if obj.user.get_full_name %}<p>Author: {{ obj.user.get_full_name }}</p>{% endif %}
        {{ obj.get_markdown|truncatechars_html:120 }}
        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
      </div>
    </div>
  </div>
<hr/>
</div>
{% endfor %}


<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>




</div>

{% endblock content %}